version: 2
jobs:
  build-and-test:
    macos:
      xcode: "13.1.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Fastlane
          command: fastlane scan
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
